### ISSUE TITLE
Link to Stackblitz

### ISSUE THREAD

**Issue by KaanBaylan** [rstropek-teaching/turmrechnen-quiz-4ahif-KaanBaylan#1]
Dear Mr. Stropek,

here is the link to my solution with Stackblitz:
https://kaanbaylan-turmrechnen.stackblitz.io

Greetings,
Baylan Kaan

**Comment by rstropek** [comment]
Hi @KaanBaylan 

Well done. Your extra point is secured.

Greetings,
Rainer Stropek.

**Comment by rstropek** [comment]
Ups, I missed one bug. The *calculate* button is not disabled if the form content is invalid. Fix that and the extra point is yours.

Greetings,
Rainer Stropek.

**Comment by KaanBaylan** [comment]
Sorry that i do this so late. 
I didn't notice you reopened the Issue 😄 

I fixed it!

Greetings,
Kaan Baylan

**Comment by rstropek** [comment]
Well done, your extra point is secured.

Greetings,
Rainer Stropek.
